Repository 6-dreaming-stars/space-star-back-matching, pull requests merged in 2024-06, with the labels that each got.

#14 Feat : 빠른 매칭 대기열 진입
  build.gradle
  src/main/java/com/spacestar/back/config/MatchingWebSocketHandler.java
  src/main/java/com/spacestar/back/config/RedisConfig.java
  src/main/java/com/spacestar/back/config/WebSocketConfig.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingController.java
  src/main/java/com/spacestar/back/quickmatching/domain/QuickMatching.java
  src/main/java/com/spacestar/back/quickmatching/dto/ChatMessageDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/QuickMatchingEnterReqDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/WebSocketInfo.java
  src/main/java/com/spacestar/back/quickmatching/repository/QuickMatchingRepository.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingService.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
  src/main/java/com/spacestar/back/quickmatching/vo/QuickMatchingEnterReqVo.java
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#20 Feat : 빠른 매칭 대기 큐 진입, 매칭 수락 큐 진입
  src/main/java/com/spacestar/back/config/MatchingWebSocketHandler.java
  src/main/java/com/spacestar/back/config/RedisConfig.java
  src/main/java/com/spacestar/back/config/WebSocketConfig.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingController.java
  src/main/java/com/spacestar/back/quickmatching/domain/QuickMatchStatus.java
  src/main/java/com/spacestar/back/quickmatching/domain/QuickMatching.java
  src/main/java/com/spacestar/back/quickmatching/dto/QuickMatchingEnterReqDto.java
  src/main/java/com/spacestar/back/quickmatching/repository/QuickMatchingRepository.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingService.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#22 Feat : 빠른 매칭
  build.gradle
  src/main/java/com/spacestar/back/config/SwaggerConfig.java
  src/main/java/com/spacestar/back/global/ResponseStatus.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingController.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingSseController.java
  src/main/java/com/spacestar/back/quickmatching/converter/QuickMatchingConverter.java
  src/main/java/com/spacestar/back/quickmatching/dto/ChatMessageDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/QuickMatchingResDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/WebSocketInfo.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingService.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
  src/main/java/com/spacestar/back/quickmatching/vo/QuickMatchingReqVo.java
  src/main/java/com/spacestar/back/quickmatching/vo/QuickMatchingResVo.java
  src/main/java/com/spacestar/back/swipe/controller/SwipeController.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#26 Feat : RestTemplate 활용하여 매칭 로직 구현
  src/main/java/com/spacestar/back/config/RestTemplateConfig.java
  src/main/java/com/spacestar/back/quickmatching/converter/QuickMatchingConverter.java
  src/main/java/com/spacestar/back/quickmatching/dto/res/AuthResDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/res/ProfileResDto.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
Labels: ✨ Feature, 📬 API

#25 Feat : 카프카 메세지 등록 기능 개발
  build.gradle
  src/main/java/com/spacestar/back/config/KafkaConfig.java
  src/main/java/com/spacestar/back/kafka/controller/KafkaController.java
  src/main/java/com/spacestar/back/kafka/message/MatchingMessage.java
  src/main/java/com/spacestar/back/kafka/service/KafkaService.java
  src/main/java/com/spacestar/back/kafka/service/KafkaServiceImpl.java
  src/main/java/com/spacestar/back/swipe/service/SwipeServiceImpl.java
Labels: ✨ Feature, 📬 API

#28 Refactor: 매칭로직 관련
  build.gradle
  src/main/java/com/spacestar/back/BackApplication.java
  src/main/java/com/spacestar/back/config/RestTemplateConfig.java
  src/main/java/com/spacestar/back/feignClient/controller/AuthClient.java
  src/main/java/com/spacestar/back/feignClient/controller/ProfileClient.java
  src/main/java/com/spacestar/back/feignClient/dto/res/AuthResDto.java
  src/main/java/com/spacestar/back/feignClient/dto/res/ProfileResDto.java
  src/main/java/com/spacestar/back/feignClient/service/FeignClientService.java
  src/main/java/com/spacestar/back/feignClient/service/FeignClientServiceImpl.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingController.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingSseController.java
  src/main/java/com/spacestar/back/quickmatching/domain/MatchingScores.java
  src/main/java/com/spacestar/back/quickmatching/dto/req/QuickMatchingEnterReqDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/res/ProfileResDto.java
  src/main/java/com/spacestar/back/quickmatching/dto/res/QuickMatchingResDto.java
  src/main/java/com/spacestar/back/quickmatching/repository/MatchingScoresRepository.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingService.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
  src/main/java/com/spacestar/back/quickmatching/vo/req/QuickMatchingEnterReqVo.java
  src/main/java/com/spacestar/back/quickmatching/vo/res/QuickMatchingResVo.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#31 Fix : 스웨거 설정,응답 값 수정
  src/main/java/com/spacestar/back/config/SwaggerConfig.java
  src/main/java/com/spacestar/back/swipe/controller/SwipeController.java
  src/main/java/com/spacestar/back/swipe/dto/res/SwipeResDto.java
  src/main/java/com/spacestar/back/swipe/service/SwipeServiceImpl.java
  src/main/java/com/spacestar/back/swipe/vo/res/SwipeResVo.java
Labels: 🔨 Refactor

#33 Feat : 요청사항 수정
  src/main/java/com/spacestar/back/feignClient/service/FeignClientService.java
  src/main/java/com/spacestar/back/feignClient/service/FeignClientServiceImpl.java
  src/main/java/com/spacestar/back/global/ResponseStatus.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
  src/main/java/com/spacestar/back/swipe/repository/SwipeRepository.java
  src/main/java/com/spacestar/back/swipe/service/SwipeServiceImpl.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#39 Feat : SSE 테스트용
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingSseController.java
Labels: ✨ Feature, 📬 API

#40 Feat : SSE 메세지 보내기
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingSseController.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingService.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
  src/main/java/com/spacestar/back/swipe/service/SwipeServiceImpl.java
Labels: ✨ Feature, 📬 API

#42 Fix : SSE, FeignClient 이슈 수정
  src/main/java/com/spacestar/back/config/OpenAiConfig.java
  src/main/java/com/spacestar/back/feignClient/controller/OpenAiClient.java
  src/main/java/com/spacestar/back/feignClient/service/FeignClientServiceImpl.java
  src/main/java/com/spacestar/back/quickmatching/controller/QuickMatchingSseController.java
  src/main/java/com/spacestar/back/quickmatching/service/QuickMatchingServiceImpl.java
Labels: 🐞 BugFix

#45 Refactor : 스와이프 수락/거절
  src/main/java/com/spacestar/back/swipe/controller/SwipeController.java
  src/main/java/com/spacestar/back/swipe/repository/CustomSwipeRepository.java
  src/main/java/com/spacestar/back/swipe/repository/CustomSwipeRepositoryImpl.java
  src/main/java/com/spacestar/back/swipe/service/SwipeService.java
  src/main/java/com/spacestar/back/swipe/service/SwipeServiceImpl.java
Labels: 🐞 BugFix
